name:                haskell-todo
version:             0.1.0.0
github:              "gusbicalho/haskell-todo"
license:             BSD3
author:              "Gustavo Bicalho"
maintainer:          "gusbicalho@gmail.com"
copyright:           "2019 Gustavo Bicalho"

extra-source-files:
- README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gusbicalho/haskell-todo#readme>

ghc-options:
- -O2
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -foptimal-applicative-do

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedLabels
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - ViewPatterns

library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - aeson
  - aeson-extra
  - async
  - bcrypt
  - bytestring
  - jose
  - mtl
  - servant-auth
  - servant-auth-server
  - servant-server
  - sqlite-simple
  - text
  - time
  - wai
  - wai-logger
  - warp

executables:
  haskell-todo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts=some
    - -with-rtsopts=-N
    dependencies:
    - base
    - haskell-todo

tests:
  haskell-todo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - haskell-todo
    - bytestring
    - http-client
    - http-types
    - hspec
    - hspec-wai
    - hspec-wai-json
    - QuickCheck
    - wai
    - wai-extra
    - warp
    - servant-server
    - servant-auth
    - servant-auth-server
    - aeson
    - mtl
    - text
    - temporary
